security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: client_id_wxm
      client-secret: client_passwd_wxm
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    resource:
      #获得 Token 信息的 URL
      token-info-uri: http://127.0.0.1:7777/oauth/check_token
    # 访问令牌获取 URL，自定义的
    access-token-uri: http://127.0.0.1:7777/oauth/token
